pre-commit:
  commands:
    check:
      run: pnpm check:fix --no-errors-on-unmatched {staged_files}
      glob: "*.{js,cjs,mjs,jsx,ts,cts,mts,tsx,json,jsonc,html,css}"
      stage_fixed: true
    test:
      run: pnpm vitest related --run --passWithNoTests {staged_files}
      glob: "*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}"

commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit {1}

pre-push:
  parallel: true
  commands:
    typecheck:
      run: pnpm typecheck
    check:
      run: pnpm check --no-errors-on-unmatched
    test:
      run: pnpm test
